notifications:
  email: false
language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - cd src/
  - cp dnd_spellbook/settings/local.sample.env dnd_spellbook/settings/local.env
  - python manage.py migrate
script:
  - python manage.py test
  - flake8
