# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('level', models.IntegerField(verbose_name='Level')),
                ('cast_type', models.CharField(max_length=50, verbose_name='Cast type')),
                ('spell_range', models.CharField(max_length=50, verbose_name='Spell Range')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
