# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-15 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tools.random_token


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0003_auto_20171212_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='spellbook',
            name='token',
            field=models.CharField(default=tools.random_token.generate_random_token, max_length=32),
        ),
        migrations.AlterField(
            model_name='spellusage',
            name='spell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell_usages', to='spellbook.Spell'),
        ),
        migrations.AlterField(
            model_name='spellusage',
            name='spellbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell_usages', to='spellbook.Spellbook'),
        ),
    ]
