# Generated by Django 2.0 on 2017-12-24 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0004_auto_20171215_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellSlotsLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(verbose_name='Level')),
                ('current_capacity', models.PositiveIntegerField(default=0, null=True, verbose_name='Current capacity')),
                ('max_capacity', models.PositiveIntegerField(default=0, null=True, verbose_name='Maximum capacity')),
                ('spellbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='spellbook.Spellbook')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='spellslotslevel',
            unique_together={('spellbook', 'level')},
        ),
    ]
