# Generated by Django 2.0 on 2017-12-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0005_auto_20171224_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='components',
            field=models.CharField(default='V', max_length=10, verbose_name='Components'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='concentration',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='duration',
            field=models.TextField(default='NA', max_length=50, verbose_name='Spell Duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='material_component',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='spell',
            name='page',
            field=models.CharField(default='NA', max_length=50, verbose_name='Page (Source)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='ritual',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='school',
            field=models.TextField(default='NA', max_length=20, verbose_name='School'),
            preserve_default=False,
        ),
    ]
